In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load
import math
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import torch
import tensorflow as tf

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
!pip install notexbook-theme

     |████████████████████████████████| 48 kB 418 kB/s eta 0:00:01


In [3]:
%reload_ext notexbook

In [4]:
%texify

Segment 1: Data Structures for Algebra

-    What Linear Algebra Is
-   A Brief History of Algebra
-    Tensors
-    Scalars
-    Vectors and Vector Transposition
-    Norms and Unit Vectors
-    Basis, Orthogonal, and Orthonormal Vectors
-    Arrays in NumPy
-    Matrices
-    Tensors in TensorFlow and PyTorch

Segment 2: Common Tensor Operations

-    Tensor Transposition
-    Basic Tensor Arithmetic
-    Reduction
-    The Dot Product
-    Solving Linear Systems

Segment 3: Matrix Properties

-    The Frobenius Norm
-    Matrix Multiplication
-    Symmetric and Identity Matrices
-    Matrix Inversion
-    Diagonal Matrices
-    Orthogonal Matrices


## Tensors

- Tensors are ML generelization of vectors and matrices to any number of dimensions.
    - 1. Scalar : x
    - 2. Vector : [x1, x2, x3]
    - 3. Matrix : $$\begin{bmatrix} X1,1 & X1 & 1 \\ 3 & 0 & 1 \\ 0 & 2 & 4 \end{bmatrix}$$

### 1. Scalars

- No dimension.
- Single Number.
- Denoted in lowercase, italics.
- Should be typed, like all other tensors, {int, int32, float, short ...}.

##### Scalars in Python

In [5]:
x = 42

In [6]:
x

42

In [7]:
type(x)

int

In [8]:
y = 13

In [9]:
sum = x + y

In [10]:
x = 25.0

In [11]:
x

25.0

In [12]:
type(x)

float

##### Scalars in Pytorch

In [13]:
x_pt = torch.tensor(42)

In [14]:
x_pt

tensor(42)

##### Scalars in tensorflow

In [15]:
x_tf = tf.Variable(42)
y_tf = tf.Variable(3)

In [16]:
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int32, numpy=45>

### 2. Vectors


    - One-dimensional array of numbers.
    - Denoted in lowercase.
    - Arranged in an order, so elements can be accessed by its index.
    - Representing a point in space
    - Vector of length n represents location in n-dimensional tensor.

##### Vectors in Numpy

In [17]:
x = np.array([25, 3, 5])
x

array([25,  3,  5])

In [18]:
len(x)

3

In [19]:
x.shape

(3,)

In [20]:
type(x)

numpy.ndarray

In [21]:
x[0]

25

In [22]:
type(x[0])

numpy.int64

In [23]:
# Transposing a Vector
x_t = x.T
x_t

array([25,  3,  5])

In [24]:
x_t.shape

(3,)

In [25]:
y = np.array([[25, 3, 15]])
y_t = y.T

In [26]:
y_t

array([[25],
       [ 3],
       [15]])

In [27]:
y_t.shape

(3, 1)

##### Vectors in Pytorch and tensorflow

In [28]:
x_pt = torch.tensor([5, 10, 15])
x_tf = tf.Variable([5, 10, 15])

In [29]:
x_pt

tensor([ 5, 10, 15])

In [30]:
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 5, 10, 15], dtype=int32)>

##### L^2 Norm

In [31]:
x

array([25,  3,  5])

In [32]:
(25 ** 2 + 3 ** 2 + 5 ** 2) ** (1/2)

25.67099530598687

In [33]:
np.linalg.norm(x)
# So the vector has a length of 25.67m

25.67099530598687

##### L^1 Norm

In [34]:
x

array([25,  3,  5])

In [35]:
np.abs(25) + np.abs(3) + np.abs(5)

33

##### Squared L^2 Norm

In [36]:
x

array([25,  3,  5])

In [37]:
(25 ** 2 + 3 ** 2 + 5 ** 2)

659

In [38]:
np.dot(x.T, x)

659

##### Max Norm

In [39]:
x

array([25,  3,  5])

In [40]:
np.max([np.abs(25), np.abs(3), np.abs(5)])

25

##### Orthogonal Vectors

In [41]:
i = np.array([1, 0])
j = np.array([0, 1])

In [42]:
np.dot(i, j)

0

In [43]:
i = np.array([6, -2])
j = np.array([-4, 4])
i_j_sum = i + j

In [44]:
i_j_sum

array([2, 2])

In [45]:
i_j_sum

array([2, 2])

### 3. Matrices (Rank 2 Tensors)


    - Two-dimensional array of numbers.
    - Denoted in uppercase.

##### Matrices in numpy

In [46]:
X = np.array([[25,2], [5,26], [3,7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [47]:
X.shape

(3, 2)

In [48]:
X.size

6

In [49]:
#Select left column of matrix X
X[:,0]

array([25,  5,  3])

In [50]:
#Select middle row of matrix X.
X[1]

array([ 5, 26])

##### Matrices in Pytorch

In [51]:
X_pt = torch.tensor([[25,2], [5,26], [3,7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [52]:
X_pt[:, 1]

tensor([ 2, 26,  7])

In [53]:
X_pt.shape

torch.Size([3, 2])

##### Matrices in tensorflow

In [54]:
X_tf = tf.Variable([[25,2], [5,26], [3,7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [55]:
X_tf.shape

TensorShape([3, 2])

In [56]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [57]:
X_tf[1, :]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26], dtype=int32)>

### 4. Higher-Rank Tensors (Rank n Tensors)

In [60]:
image_pt = torch.zeros([32,28,28,3])
image_pt

tensor([[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         ...,

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          ...,
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0.

In [62]:
image_tf = tf.zeros([32,28,28,3])
image_tf

<tf.Tensor: shape=(32, 28, 28, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        ...,

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         ...,
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


   